export const KEYBOARD_MAP = {
  KeyZ: { note: 0, octave: 2 },
  KeyS: { note: 1, octave: 2 },
  KeyX: { note: 2, octave: 2 },
  KeyD: { note: 3, octave: 2 },
  KeyC: { note: 4, octave: 2 },
  KeyV: { note: 5, octave: 2 },
  KeyG: { note: 6, octave: 2 },
  KeyB: { note: 7, octave: 2 },
  KeyH: { note: 8, octave: 2 },
  KeyN: { note: 9, octave: 2 },
  KeyJ: { note: 10, octave: 2 },
  KeyM: { note: 11, octave: 2 },
  Comma: { note: 0, octave: 3 },
  KeyL: { note: 1, octave: 3 },
  Period: { note: 2, octave: 3 },
  Semicolon: { note: 3, octave: 3 },
  Slash: { note: 4, octave: 3 },
  KeyQ: { note: 5, octave: 3 },
  Digit2: { note: 6, octave: 3 },
  KeyW: { note: 7, octave: 3 },
  Digit3: { note: 8, octave: 3 },
  KeyE: { note: 9, octave: 3 },
  Digit4: { note: 10, octave: 3 },
  KeyR: { note: 11, octave: 3 },
  KeyT: { note: 0, octave: 4 },
  Digit6: { note: 1, octave: 4 },
  KeyY: { note: 2, octave: 4 },
  Digit7: { note: 3, octave: 4 },
  KeyU: { note: 4, octave: 4 },
  KeyI: { note: 5, octave: 4 },
  Digit9: { note: 6, octave: 4 },
  KeyO: { note: 7, octave: 4 },
  Digit0: { note: 8, octave: 4 },
  KeyP: { note: 9, octave: 4 },
  Minus: { note: 10, octave: 4 },
  BracketLeft: { note: 11, octave: 4 },
  BracketRight: { note: 0, octave: 5 },
} as const;

export const KEY_DISPLAY_LABELS: { [key: string]: string } = {
  KeyZ: "z",
  KeyS: "s",
  KeyX: "x",
  KeyD: "d",
  KeyC: "c",
  KeyV: "v",
  KeyG: "g",
  KeyB: "b",
  KeyH: "h",
  KeyN: "n",
  KeyJ: "j",
  KeyM: "m",
  Comma: ",",
  KeyL: "l",
  Period: ".",
  Semicolon: ";",
  Slash: "/",
  KeyQ: "q",
  Digit2: "2",
  KeyW: "w",
  Digit3: "3",
  KeyE: "e",
  Digit4: "4",
  KeyR: "r",
  KeyT: "t",
  Digit6: "6",
  KeyY: "y",
  Digit7: "7",
  KeyU: "u",
  KeyI: "i",
  Digit9: "9",
  KeyO: "o",
  Digit0: "0",
  KeyP: "p",
  Minus: "-",
  BracketLeft: "[",
  BracketRight: "]",
} as const;
